### ISSUE TITLE
BaseformTokenFilter sets incorrect offsets for inserted baseforms

### ISSUE THREAD

**Issue by mikemccand** [jprante/elasticsearch-analysis-baseform#11]
At https://github.com/jprante/elasticsearch-analysis-baseform/blob/master/src/main/java/org/xbib/elasticsearch/index/analysis/baseform/BaseformTokenFilter.java#L43 we set the offsets from the saved token, but when the token was saved, we never set its offsets, so these offsets are always 0, which is dangerous since parts of Lucene assume offsets move forwards.

I think to fix this we should just remove that one line ... because the `restoreState(current)` right above it will already set the correct offsets.

**Comment by jprante** [comment]
Thanks for the pointer!
