### ISSUE TITLE
Installation fails with file not found

### ISSUE THREAD

**Issue by rndstr** [jprante/elasticsearch-analysis-baseform#9]
Seems this is no longer available at this URL 

http://xbib.org/repository/org/xbib/elasticsearch/plugin/elasticsearch-analysis-baseform/1.3.0.0/elasticsearch-analysis-baseform-1.3.0.0-plugin.zip

**Comment by jprante** [comment]
I wiped the plugin repo by accident, sorry. Now 1.3.0.0 is restored, and an update to 1.4.0.0 is also available.

**Comment by rndstr** [comment]
No big deal, thanks for quickly restoring it!
